Another robustness issue
... though I don't know what can cause JSONObject to be null

java.util.concurrent.ExecutionException: net.sf.json.JSONException: null object
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.jenkinsci.infra.log.App.main(App.java:54)
Caused by: net.sf.json.JSONException: null object
	at net.sf.json.JSONObject.verifyIsNull(JSONObject.java:2424)
	at net.sf.json.JSONObject.size(JSONObject.java:2111)
	at java.util.HashMap.putMapEntries(HashMap.java:500)
	at java.util.HashMap.<init>(HashMap.java:489)
	at org.jenkinsci.infra.log.Scrambler.handleJSONObject(Scrambler.java:78)
	at org.jenkinsci.infra.log.Decrypter.process(Decrypter.java:87)
	at org.jenkinsci.infra.log.App$1.run(App.java:42)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)