More defensive check
java.util.concurrent.ExecutionException: net.sf.json.JSONException: JSONObject["plugins"] is not a JSONArray.
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.jenkinsci.infra.log.App.main(App.java:54)
Caused by: net.sf.json.JSONException: JSONObject["plugins"] is not a JSONArray.
	at net.sf.json.JSONObject.getJSONArray(JSONObject.java:1735)
	at org.jenkinsci.infra.log.Scrambler.handleJSONObject(Scrambler.java:72)
	at org.jenkinsci.infra.log.Decrypter.process(Decrypter.java:96)
	at org.jenkinsci.infra.log.App$1.run(App.java:42)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)